const menu = [
    {
        id: 1,
        title: 'Capuchino',
        category: 'Hot',
        price: 5.49,
        img: './images/hot2.jpg',
        desc: `Variations of the drink involve the use of cream instead of milk, using non-dairy milk substitutes and flavoring with cinnamon or chocolate powder. `,
      },
    {
      id: 2,
      title: 'Ice milk coldbrew',
      category: 'Ice',
      price: 5.49,
      img: './images/ice2.jpg',
      desc: `Cold brew concentrate is cold brew with a very high coffee to water ratio `,
    },
    
    {
      id: 3,
      title: 'Latte',
      category: 'Hot',
      price: 5.49,
      img: './images/hot3.jpg',
      desc: `Espresso is combined with steamed milk to create a creamy smooth coffee beverage with a delicate espresso flavor`,
    },
    {
      id: 4,
      title: 'Sea salt Machiato',
      category: 'Hot',
      price: 5.99,
      img: './images/hot4.jpg',
      desc: `A macchiato is a much stronger coffee drink than a latte, offering more bold flavors and caffeine. `,
    },
    {
      id: 5,
      title: 'Egg coffee',
      category: 'Special',
      price: 6.69,
      img: './images/spec4.jpg',
      desc: `Speacial coffee made with egg fluffy layer on the top .`,
    },
    {
      id: 6,
      title: 'Vietnamese ice coffee',
      category: 'Ice',
      price: 5.49,
      img: './images/ice3.jpg',
      desc: `VietNamese traditional coffee made with condensed milk and ice`,
    },
    {
      id: 7,
      title: 'Bac xiu',
      category: 'Special',
      price: 5.49,
      img: './images/spec2.jpg',
      desc: `Put it all together and you get “a white glass with a little amount of coffee”. `,
    },
    {
      id: 8,
      title: 'Slow Bac Xiu',
      category: 'Special',
      price: 6.69,
      img: './images/spec1.jpg',
      desc: `Special version of Bac xiu with three layers and more coffee.  `,
    },
    {
      id: 9,
      title: 'Vietnamese drip',
      category: 'Special',
      price: 6.49,
      img: './images/spec3.jpg',
      desc: `Vietnamese coffee is traditionally brewed in a phin – a small metal cup that fits over a mug or cup– and brews incredibly slow.`,
    },
    {
        id: 10,
        title: 'Americano',
        category: 'Hot',
        price: 3.99,
        img: './images/hot1.jpg',
        desc: `An Americano contains espresso and hot water.`,
      },
  ];
  export default menu;
  